#pragma once


#ifdef WIN32
	#define CONSOLE_COLOR_OFF
	#define CONSOLE_COLOR_BOLD
	#define CONSOLE_COLOR_RED
	#define CONSOLE_COLOR_GREEN
	#define CONSOLE_COLOR_YELLOW
	#define CONSOLE_COLOR_BLUE
	#define CONSOLE_COLOR_MAGENTA
	#define CONSOLE_COLOR_CYAN
	#define CONSOLE_COLOR_WHITE
	#define CONSOLE_COLOR_DBOLD
	#define CONSOLE_COLOR_NBOLD
	#define CONSOLE_COLOR_UNDERLINE
	#define CONSOLE_COLOR_NUNDERLINE
	#define CONSOLE_COLOR_INVERSE
	#define CONSOLE_COLOR_NINVERSE
	#define CONSOLE_COLOR_BREAK
	#define CONSOLE_COLOR_NORMAL
    #define CONSOLE_COLOR_GREY
#else
	
	#define CONSOLE_COLOR_OFF "\033[0m"
	#define CONSOLE_COLOR_BOLD "\033[1m"
	#define CONSOLE_COLOR_RED "\033[1;31m"
	#define CONSOLE_COLOR_GREEN "\033[0;32m"
	#define CONSOLE_COLOR_YELLOW "\033[0;33m"
	#define CONSOLE_COLOR_BLUE "\033[1;34m"
	#define CONSOLE_COLOR_MAGENTA "\033[0;35m"
	#define CONSOLE_COLOR_CYAN "\033[1;36m"
	#define CONSOLE_COLOR_GREY "\033[1;30m"
	#define CONSOLE_COLOR_WHITE "\033[37m"
	
	#define CONSOLE_COLOR_DBOLD "\033[2m"
	
	#define CONSOLE_COLOR_NBOLD "\033[22m"
	
	#define CONSOLE_COLOR_UNDERLINE "\033[4m"
	
	#define CONSOLE_COLOR_NUNDERLINE "\033[4m"
	
	#define CONSOLE_COLOR_INVERSE "\033[7m"
	
	#define CONSOLE_COLOR_NINVERSE "\033[7m"
	
	#define CONSOLE_COLOR_BREAK "\033[m"
	
	#define CONSOLE_COLOR_NORMAL "\033[0m"
#endif

